/*
**  Copyright 2022 bitValence, Inc.
**  All Rights Reserved.
**
**  This program is free software; you can modify and/or redistribute it
**  under the terms of the GNU Affero General Public License
**  as published by the Free Software Foundation; version 3 with
**  attribution addendums as found in the LICENSE.txt
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU Affero General Public License for more details.
**
**  Purpose:
**    Define the Hyun_first application
**
**  Notes:
**   1. This file was automatically generated by cFS Basecamp's app
**      creation tool. If you edit it, your changes will be lost if
**      a new app with the same name is created. 
**
*/

#ifndef _hyun_first_app_
#define _hyun_first_app_

/*
** Includes
*/

#include "app_cfg.h"

/***********************/
/** Macro Definitions **/
/***********************/

//EX1
/*
** Events
*/

#define HYUN_FIRST_INIT_APP_EID    (HYUN_FIRST_BASE_EID + 0)
#define HYUN_FIRST_NOOP_EID        (HYUN_FIRST_BASE_EID + 1)
#define HYUN_FIRST_EXIT_EID        (HYUN_FIRST_BASE_EID + 2)
#define HYUN_FIRST_INVALID_MID_EID (HYUN_FIRST_BASE_EID + 3)
#define HYUN_FIRST_SET_PARAM_EID   (HYUN_FIRST_BASE_EID + 4)
//EX1

/**********************/
/** Type Definitions **/
/**********************/


/******************************************************************************
** Command Packets
** - See EDS command definitions in hyun_first.xml
*/


/******************************************************************************
** Telmetery Packets
** - See EDS command definitions in hyun_first.xml
*/


/******************************************************************************
** HYUN_FIRST_Class
*/
typedef struct
{

   /* 
   ** App Framework
   */ 
    
   INITBL_Class_t  IniTbl; 
   CMDMGR_Class_t  CmdMgr;
   
   /*
   ** Command Packets
   */

 
   /*
   ** Telemetry Packets
   */
   
   HYUN_FIRST_StatusTlm_t  StatusTlm;
   
   /*
   ** HYUN_FIRST State & Contained Objects
   */ 
           
   uint32           PerfId;
   CFE_SB_PipeId_t  CmdPipe;
   CFE_SB_MsgId_t   CmdMid;
   CFE_SB_MsgId_t   SendStatusMid;
   
} HYUN_FIRST_Class_t;


/*******************/
/** Exported Data **/
/*******************/

extern HYUN_FIRST_Class_t  Hyun_first;


/************************/
/** Exported Functions **/
/************************/


/******************************************************************************
** Function: HYUN_FIRST_AppMain
**
*/
void HYUN_FIRST_AppMain(void);


/******************************************************************************
** Function: HYUN_FIRST_NoOpCmd
**
*/
bool HYUN_FIRST_NoOpCmd(void *ObjDataPtr, const CFE_MSG_Message_t *MsgPtr);


//EX2
/******************************************************************************
** Function: HYUN_FIRST_ResetAppCmd
**
*/
bool HYUN_FIRST_ResetAppCmd(void *ObjDataPtr, const CFE_MSG_Message_t *MsgPtr);



/******************************************************************************
** Function: HYUN_FIRST_SetParam
**
*/
bool HYUN_FIRST_SetParamCmd(void *ObjDataPtr, const CFE_MSG_Message_t *MsgPtr);
//EX2

#endif /* _hyun_first_ */
